### PR TITLE
Change FPU reduction, add search depth tracking

### PR DESCRIPTION
**Pull request by jkiliani**
Changes the FPU reduction method to one which simulates virtual loss, and increases this simulated VL proportional to the root of total visit count. This method should work well for both low and high visit counts, since it prunes very little at the root level, but a lot deep in the search tree. Currently set value for cfg_fpu_reduction is pure guess right now, I'm just starting to test this (along with puct).

Constitutes another rebase from #364.

### CODE REVIEW

**Comment by Akababa** [comment]
If the FPU reduction and search depth tracking are independent, I'd advise separating them into two PRs. Also this only prints when the depth of the lowest leaf increases, as opposed to whenever the PV changes (which is preferable IMO)

**Comment by jkiliani** [comment]
True, but the part about the preferable max depth is debatable... this is strictly monotonous, which is necessary since the regular info output triggers whenever search depth increases.

**Comment by Akababa** [comment]
Oh, I agree on making depth non-decreasing, I just think it should be printed whenever the PV changes (for example if the network finds a new best move, it'll take a while to catch up the the previous max_depth)

**Comment by mooskagh** [comment]
When I debugged the tensorflow implementation, I noticed that lowering PUCT
really helps on low playouts, but not on high.

Basically at low playouts the  sqrt(total N)/N  part never went low enough
to lower importance of the policy head, so even if after trying very
probably move Q went considerably lower, it still spent another hundred of
visits still exploring the same node.

**Comment by jkiliani** [comment]
Thanks, good point. I'll run a test at 800 playouts to see what I can find out about this.

**Comment by jkiliani** [comment]
Tuning tournament with Id 194:
```
Rank Name                          Elo     +/-   Games   Score   Draws
   1 lc_next_6                      43      65      57   56.1%   49.1%
   2 lc_00_6                        31      58      57   54.4%   59.6%
   3 lc_00                          12      71      57   51.8%   40.4%
   4 lc_next                         6      68      58   50.9%   43.1%
   5 lc_05                          -6      55      57   49.1%   63.2%
   6 lc_10_6                       -12      64      57   48.2%   50.9%
   7 lc_10                         -24      69      58   46.6%   41.4%
   8 lc_05_6                       -49      64      57   43.0%   50.9%
```
While this is obviously not good enough to prove the statistical significance of a new method, I have to admit I'm disappointed here. The FPU reduction method I proposed appears to be actually weaker, at least for this first net. I'm going to run one more test, this time with Id 202. If it turns out similar I'm closing #438.

An at least potentially useful side result here seems to be that lower PUCT appears to work at 800 playouts as well, although the relative improvement looks a lot smaller than the 100 Elo measured by @gcp. Again, more data is needed. At least, fixing the unintended virtual loss currently in /master and /next does not appear to weaken then engine by any significant margin, when 800 visits are used.

**Comment by jkiliani** [comment]
Tuning tournament with Id 202:
```
Rank Name                          Elo     +/-   Games   Score   Draws
   1 lc_00_6                        73      58      63   60.3%   54.0%
   2 lc_next_6                      33      62      63   54.8%   49.2%
   3 lc_next                        28      65      63   54.0%   44.4%
   4 lc_05_6                        17      65      63   52.4%   44.4%
   5 lc_10                          -6      66      62   49.2%   43.5%
   6 lc_05                         -22      53      63   46.8%   61.9%
   7 lc_00                         -44      68      63   43.7%   39.7%
   8 lc_10_6                       -80      73      62   38.7%   32.3%
```
It appears that my idea with simulating virtual loss for FPU reduction does not work reliably, so I'll close this PR. However, it does look like fixing the virtual loss bug and using puct=0.6 along with dynamic parent eval works very well, for self-play at least.

While it seems plausible to me from @jjoshua2's matches against other engines that lowering PUCT makes Leela slightly more tactically vulnerable, it also seems to significantly improve her positional play.

**Pull request closed without merging**
