### PR TITLE
Detect draws due to insufficient mating material

### LINKED ISSUE #89: Insufficient mating material rule is not observed in selfplay
Position::is_draw() doesn't cover draw by insufficient mating material (such as K+N v K or even K v K). Is this intentional? It seems like a lot of the longer games reach such positions and then continue until 3-fold rep or 50-move or 450-ply draw, which is wasteful.

On the one hand, the conditions for "insufficient mating material" (theoretical impossibility of a checkmate) are human knowledge, but on the other hand, they are, in fact, part of the official rules.

### PR DESCRIPTION
**Pull request by evalon32**
fixes #89

### CODE REVIEW

**Comment by jjoshua2** [comment]
Factoring it out into a new method is nice, especially once it gets this complicated with arbitrary count of bishops on the same color.
It seems there is no need for the count(bishops) in case 2 since it is already covered by the case 3 rule, unless you are chasing a small speed gain there.
also, why isn't popcount(pos.pieces) used? like is used for checking how many pieces are left for syzygy tb probe?

**Comment by evalon32** [comment]
@jjoshua2 I'm checking for a single bishop in case 2 because case 3 is only triggered when there's more than 3 pieces.
Regarding popcount: `popcount(pieces())` should work, but is there some advantage to it? `count<ALL_PIECES>()` is a single ADD operation.

This brings up something else: the default configuration doesn't use builtin popcount, even though my CPU definitely supports it (and Stockfish's build does use it).

**Comment by Error323** [comment]
Hi @evanlon32,

This looks good! I have two points:

1. Could you add a unit test for it? Just using a few FEN positions. See `tests/perf_test.cpp` for an example.

2. I think we should hold off merging until we bump to a strict new version. This PR will change the statistics landscape drastically.

**Comment by jjoshua2** [comment]
1 for sure. 2 I could go either way. It will boost speed immediately and we still have few contributors and they are mostly people very active here imo.

**Comment by Error323** [comment]
Hmm that's a fair point @jjoshua2.

**Pull request closed without merging**
