### PR TITLE
Use independent game trees for white and black during training

### PR DESCRIPTION
**Pull request by Tilps**
Using two trees improves the power of Dirichlet noise in two ways.
1) By having an intervening move, the amount of tree reuse is often smaller.
2) The noise for one player is completely independent of the other - so if it results in a discovery, the other player won't have a tree already planned based on the same noise. This should encourage more noise effect to potentially find a counter discovery.

It has some downsides obviously.
1) Memory usage increases. (I don't think this is significant since we use pretty low nodes for training.)
2) A reduction in performance.  I have not quantified it, but I do not expect it to be significant. In part because there still is some tree reuse happening, and secondly because the NNcache is shared between both trees.

This concept came up during a discussion about ELF yesterday - I've not actually worked out whether ELF actually does this, but I suspect it does...

### CODE REVIEW

**Comment by Tilps** [comment]
Some very rough performance testing suggests old code gets less than 10% more moves per hour than new code. (Obviously game duration varies significantly based on ply, so in the interest of time I just did a time per move estimation based on 3 games with the change, and 3 games at head - each starting with a fresh instance of the client to ensure NNcache didn't follow from one game to the next.)

**Comment by Akababa** [comment]
Dirichlet noise is only applied at the root, so why should tree re-use affect anything other than performance?

**Comment by killerducky** [comment]
If we want to do something to increase the effectiveness of Dirichlet noise, I would prefer to turn off tree-reuse entirely. Most of the performance should be recovered due to NNCache hits.

**Comment by Tilps** [comment]
So, in what is probably an example of the size of my error bars.  Disabling tree reuse entirely comes up as ~10% more moves per hour than the original single tree. (So it certainly seems plausible that NN cache dominates the performance characteristics.)

**Comment by killerducky** [comment]
#536 is a better candidate.

**Pull request closed without merging**
