### PR TITLE
added ability to defind num of threads

### PR DESCRIPTION
**Pull request by hurnhu**
you can now define # threads with the --threads option, it defaults to 2

### CODE REVIEW

**Comment by cn4750** [comment]
I believe that threads were set to one on purpose and not exposed such that training stayed deterministic.
If you want to take advantage of more of your hardware's threads, run more clients.

**Comment by jjoshua2** [comment]
This is extremely similar to existing #201

**Comment by hurnhu** [comment]
yeah i didnot even see that other pr

**Comment by killerducky** [comment]
I think what we want is a way to tell client to run multiple separate instances of `lczero -t1 etc`. LZGo does this with `autogtp -g#`.

**Pull request closed without merging**
