### PR TITLE
CODE OF CONDUCT

### PR DESCRIPTION
**Pull request by AMN3I**

### CODE REVIEW

**Comment by killerducky** [comment]
Something weird is going on when I changed base to next. Can you merge on your side?

**Comment by AMN3I** [comment]
OK

**Comment by AMN3I** [comment]
view https://github.com/glinscott/leela-chess/pull/424

**Comment by AMN3I** [comment]
and https://github.com/glinscott/leela-chess/pull/434

**Comment by killerducky** [comment]
Dup of #424.

**Pull request closed without merging**
