### PR TITLE
Make fpu dynamic_eval an option, and enable it.

### PR DESCRIPTION
**Pull request by Tilps**
So, I put in the PR to disable this last night concerned that it might have been unintended.

But I've done over 150 self play games at fixed visit count (tried 75 at 1600 and another 75 at 160 and they both agree) and there looks to be somewhere around a 50 elo gain with dynamic eval.

Rather than just revert my last PR, I've made it an config parameter - because there is the potential that it doesn't play well with fpu_reduction, and that fpu_reduction on its own might be an improvement even further still.

### CODE REVIEW

**Comment by killerducky** [comment]
You added a config parameter but there's no way to change it. I want to get away from command line options and use UCI, but seems we're still not ready. So how about a command line option? `--fpu_dynamic_eval [on|off]`?

**Comment by killerducky** [comment]
I just noticed there isn't one for cfg_fpu_reduction either. I'm debating if we want to expose these and similar ones. Eventually we want to provide an engine that is already tuned well, but we are changing rapidly. It might make sense to expose these for now.

Looking for feedback.

**Comment by jjoshua2** [comment]
I need them command line options so I can tune them with clop I'm pretty
sure. Definitely need them exposed but could maybe use a ifdef tuning

**Comment by Tilps** [comment]
Yes, only reason I didn't add command line parameter here, was because the other one didn't have one yet.

**Comment by killerducky** [comment]
I spoke with Gary on discord. He prefers to just go with this PR as is, no command line. We can think about how to enable clop tuning later.

Also v0.5 has been out for 2 days now and some people are reporting it is stronger due to the (unintended) FPU change from v0.4.

**Pull request merged**
