### PR TITLE
Sanity check to help protect against potential future crashes caused by pruning.

### PR DESCRIPTION
**Pull request by Tilps**

### CODE REVIEW

**Comment by Tilps** [comment]
Looks like this might be a real bug fix for anyone using threads > 1.  Multiple threads can cause the visit limit to be breached, resulting in total pruning leading to the crash.  Would be much more frequent for tiny visit limit is relevant because larger visit limits generally move on to the next move before getting close to the limit because of the very pruning which leads to the crash.

**Comment by killerducky** [comment]
Check what LZGo recently changed:
https://github.com/gcp/leela-zero/commit/b0de331742f42972190984b151bdb876d7d10170

I think we should use that so we remain as close as possible to LZGo. It's basically the exact same thing done in a different spot,

**Comment by Tilps** [comment]
Yeah, I did it this way because it was safer smaller change.  I can change it to the LZGo way, but not for a few hours at least.

**Comment by killerducky** [comment]
I'm at home now so I did #304. Thanks again for pointing out this is an issue for LZChess.

**Pull request closed without merging**
