### PR TITLE
Fix compiling, check policy/value plane count

### PR DESCRIPTION
**Pull request by Ttl**
OpenCLScheduler was missing in Makefile.

Random weights in lczero-weights repository have incorrect value and output heads. Check the count before loading to avoid crashing.

### CODE REVIEW

**Comment by killerducky** [comment]
Is this related to the network giving not so random outputs? #68

**Comment by Ttl** [comment]
I don't know if the network used in self-plays is the same random network that is in the lczero-weights repository. If it is then this is very likely the source of the problem. For me lczero just crashed using random weights and I haven't seen anyone complaining about crashes.

**Comment by Error323** [comment]
Hi @Ttl,

The random weights are from before the #43 realization. The nof output planes have been adjusted to 32 for each head since then. This is a good sanity check though thanks! Also we should delete those weights from the repo.

**Comment by glinscott** [comment]
Thanks!

**Pull request merged**
