### PR TITLE
Fix the visual studio project file for new source code.

### PR DESCRIPTION
**Pull request by Tilps**

### CODE REVIEW

**Comment by Tilps** [comment]
Looks like this is a dupe of #356 - although I did add a missing header file as well.

**Comment by Akababa** [comment]
Yep, good catch, I'll close mine.

**Comment by killerducky** [comment]
@Tilps will merge this now, but is there a way we can get Travis/appveyor to catch this?

**Comment by Tilps** [comment]
might be confusing having two separate appveyor configs to build using visual studio 2 different ways - but I guess its plausible.

**Pull request merged**
