### PR TITLE
Move Network::initialize() to UCI::loop()

### PR DESCRIPTION
**Pull request by kostuek**
Start Network::initialize() as an async task after entering UCI::loop(). Wait for the task to complete after receiving "isready", do it only once. This should speed up the engine booting and increase the UCI protocol compatibility. Tested in Ubuntu for the intended functionality.

### CODE REVIEW

**Comment by killerducky** [comment]
* Please keep consistent coding style, open brace on same line not newline
* This breaks the client because it does not call "isready" (even though that is a violation of UCI). We need to either update client to call isready for both matches and self-play, and/or add the wait_init code to the "go" and "train" commands. Probably doing both is best because some other GUIs might make this same mistake.

@TheAnswer does this look ok for multi-threading? I can't think of any problems outside what I mentioned.

**Comment by kostuek** [comment]
Ah, I forgot about the client for some reason... I'm not a big fan of adding wait_init to "go" and "train", especially to "go" since it will be called often during a game. I think I'll try to utilize the "--uci" command line parameter instead, so the engine behavior will not change if no "--uci" is used.

**Comment by killerducky** [comment]
I'd like to get rid of --uci because we're supposed to be a UCI engine after all. How about this instead: client could be modified to call "isready" for the match case. For the "train" case you could call initialize from there before actually doing the self play game.

**Comment by kostuek** [comment]
I need to test/debug the client. After setting up a local server, I think I managed to upload 2 networks to it, but now I'm lost. How do I let it play some match games (training works with the actual online server, so I only need to test matches)?

**Comment by killerducky** [comment]
What I've done for testing LZGo is modify the client to ignore what the server is saying, do a match, and skip the upload to server step. In general we could really use some better methods to test these things. There could be a `client -test` switch that makes it act differently or something?

If you're able to get a local server going I guess that's even better, but of course more difficult. I haven't tried it myself. Maybe you could add step-by-step instructions somewhere? This PR, one of the READMEs, or the wiki?

**Comment by kostuek** [comment]
Actually, the instructions how to set up a server are in the server readme, and also how to upload a network to it and to connect with the client. What is not there is how to proceed. Somehow I need to tell the server "we are doing match games now". I'll post here if I manage to do so.

**Comment by kostuek** [comment]
All done. Tested in ubuntu with the online server, client behaves in training and match games as intended. 
I'll add some info how to test locally to the server readme in the next days.

**Comment by jjoshua2** [comment]
I'd worry that a non compliant GUI wouldn't allow command line flags, like chessbase/infinity. But until we find one that isn't compliant we don't need a flag, and then we can see if it allows command lines, and is a popular enough GUI to support.

**Comment by killerducky** [comment]
Fritz doesn't allow flags, and right now it also requires `--uci` (so people use inbetween). But Fritz is UCI compliant, so we should optimize for the Fritz case which is doing nothing wrong, and put the burden on whatever GUI out there is not UCI compliant *and* doesn't allow flags.

**Comment by kostuek** [comment]
I'm kind of simple minded there - if a GUI does not follow the protocol, it should be a problem of the GUI, not of anyone else. It is not possible to catch every misbehavior out there anyways.

And I just realized, I should probably remove if (!cfg_noinitialize) from net_init() in UCI.cpp? Is it set to false by the the -uci option?

**Comment by jjoshua2** [comment]
I think I'm agreeing with you @killerducky. I really only care about supporting Fritz/InfinityChess, Arena, and Cutechess. Not needing the --uci seems good so inbetween is not needed with Fritz.

**Comment by kostuek** [comment]
Removed --uci and also cfg_noinitialize since they did not do anything anymore.

**Comment by kostuek** [comment]
Added sleep to the waiting loop.

**Comment by kostuek** [comment]
Removed the changes in client/main.go again since they are not needed with netinit.get() in go token.

**Pull request closed without merging**
