### PR TITLE
Reduce first play urgency

### PR DESCRIPTION
**Pull request by jkiliani**
Reduces the urgency of the UCT search to expand unvisited nodes, except for noised root nodes. Also tunes cfg_puct, the parameter controlling exploration in the search, increasing its value. Based on gcp/leela-zero@6b56e3f and gcp/leela-zero@0c8cd6a.

### CODE REVIEW

**Comment by jkiliani** [comment]
I created this pull so more people are able to evaluate the effects of FPU reduction. At the moment I'm still running tuning tests for cfg_puct, for now I inserted what seems the best value of tests so far.

**Comment by jkiliani** [comment]
I guess this now needs a rebase? I'll have to do this anyway to continue the tuning tests for v4 nets, will continue the tests when I'm ready with that.

**Comment by jkiliani** [comment]
Based on the final results of the tuning run, I changed cfg_puct to 0.9, where I measured an average 88 Elo gain compared to the current master branch.

**Comment by Error323** [comment]
Thanks @jkiliani nice!

**Comment by jkiliani** [comment]
Thanks for merging, glad to help!

**Comment by glinscott** [comment]
Wow, thanks for all the effort and investigation!!

**Pull request merged**
