### PR TITLE
Guide users to client directory in README.md

### PR DESCRIPTION
**Pull request by Prcuvu**
It confused me for a while since I did not know where to find the client initially. It seems like a good idea to guide users to client directory in README.

### CODE REVIEW

**Comment by Error323** [comment]
Could you create a clickable link to the readme? Like so: [README](https://github.com/glinscott/leela-chess/blob/master/go/src/client/README.md)

**Comment by mooskagh** [comment]
It also confused me a lot what I had to build in order to help with the
training.

It turned out that I had to build/use both go/client and lczero, but not
go/server and something written in python.
It probably sounds obvious when you know it, but without knowing it it was
really confusing.
We should put a clear text somewhere, that "To help with training, you have
to build a client (a program written in Go) and lczero (C++ binary)".

Also it's not entirely clear what dependencies I had to install. For
example, it says I had to install "Tensorflow (for training)", but I'm not
sure whether what I do by running ./client is called training or not. Also
it was not clear why both OpenCL and Tensorflow are listed. Why suddenly
client documentation is located separately and the client needs Golang
which was not listed in dependencies.

I even asked in groups whether I only needed a client or something else (I
thought that lczero is a server, so I confused everyone by asking "do I
also need a server"), and got the answer that I only need client. I built a
client, and it said it couldn't find ./lczero, and only then it I realized
that ./lczero is what actually plays games.

In "contributing" section it says:
*The server is live at http://162.217.248.187/ <http://162.217.248.187/>.
Please download the client and give it a try.*
I follow the link and see no way to download a client. (Also it sounds like
a client is all I need). Actually, I'm not sure whether it's possible to
download a compiled client from somewhere, or everyone still builds it
themselves.

There are (I guess?) pre-built binaries for Windows, but to find them, a
person has to read through a forum, which not everyone is keen doing. And
also, not everyone speaks English well enough to read all instructions, but
pretty much everyone would know what "Download (version for Windows)" meant.

For people not familiar with leela-zero/ML/programming it's all very
confusing.

**Comment by Error323** [comment]
@mooskagh You're right, this is very unclear. I'll redo the readme when I have some time. It's important that people understand what they need to do. Thanks!

**Comment by Prcuvu** [comment]
@Error323 Done.

**Comment by Prcuvu** [comment]
> it says I had to install "Tensorflow (for training)"

TensorFlow training is something totally different from the online training client. I was confused as well in the beginning.

> *Please download the client and give it a try.* I follow the link and see no way to download a client.

The instruction is very misleading and I wasted a lot of time trying to find the nonexistent download link on the server. That is why I decided to make this Pull Request.

**Comment by mooskagh** [comment]
Oops, sorry, I didn't even notice it was a PR, I just got some notification of confusing documentation on my email (thought it was an issue/groups message) and replied with a dump of what I think about it. :)

I should have started a separate issue/mail thread about that.

**Comment by glinscott** [comment]
Thanks, sorry I didn't merge this one - we've got the wiki for helping people get started now :).

**Pull request closed without merging**
