### PR TITLE
Refactor tempdecay code.

### PR DESCRIPTION
**Pull request by killerducky**
Preparing to add some sanity floors to prevent occasional blunders.

I started on this awhile ago but haven't had time to pick good values for cfg_rand_visit_floor and cfg_rand_eval_maxdiff. But I think the refactor is good so I'd like to put this in before I forget about it.

### CODE REVIEW

**Comment by killerducky** [comment]
I verified this is functionally the same by doing a few tests like this with the PR and current next and diffing the logs:

```
cat commands.txt 
position startpos moves d2d4 g8f6 c2c4 e7e6 b1c3 d7d5 c4d5 e6d5 c1g5 f8e7 e2e3 e8g8 f1d3 c7c5 d4c5 e7c5 g1e2 c5e7 e1g1 b8c6 a1c1 h7h6 g5f4 a7a6 h2h3 c8e6 f4h2 d5d4 e2d4 c6d4 e3d4
go nodes 100
position startpos moves d2d4 g8f6 c2c4 e7e6 b1c3 d7d5 c4d5 e6d5 c1g5 f8e7 e2e3 e8g8 f1d3 c7c5 d4c5 e7c5 g1e2 c5e7 e1g1 b8c6 a1c1 h7h6 g5f4 a7a6 h2h3 c8e6 f4h2 d5d4 e2d4 c6d4 e3d4 d8d4

cat commands.txt | ./lczero -t1 -s1 --tempdecay=10 -l temp_test.log
```

**Comment by dubslow** [comment]
I have concerns about this. For instance discovered attacks, Leela still seems to be missing a lot of 1ply tactics.

For instance, with white to move in [this position](https://lichess.org/mbWjiT93#106), the correct move is the discovered attack tactic Rg6+, but Leela missed it after at least a thousand playouts. I'm quite worried that this sort of move would be excluded by these new bounds, even though it's not an insane blunder (quite the opposite in fact).

**Comment by killerducky** [comment]
I think you're worried about self-play training? This is for match play only.

**Comment by dubslow** [comment]
Match play uses temperature at all? I guess you mean for things like lichess bot?

And yes I was worried about training, but this is probably reasonable for match play then.

**Comment by killerducky** [comment]
https://github.com/glinscott/leela-chess/blob/51e03d63ba5ef9fe504bb0def9677c634a5f8bdb/go/src/server/main.go#L251

**Comment by jkiliani** [comment]
I think your code looks very nice, and it adds functionality to limit its strength loss in multiple possible ways. It's a good question whether both cfg_rand_visit_floor and cfg_rand_eval_maxdiff are necessary, in practise we would likely get away with only using one.

**Pull request merged**
