### PR TITLE
Use get_input_channels() rather than MAX_INPUT_CHANNELS when populating network input array.

### PR DESCRIPTION
**Pull request by Tilps**
(This is just a quick implementation of the fix KillerDucky proposed in #576)

### CODE REVIEW

**Comment by killerducky** [comment]
I was doing one too but let's use your. How about some comments like this:
```
+    // NNPlanes is a static structure that has room for the maximum
+    // number of planes (V1). So here use MAX_INPUT_CHANNELS.
+    // (It might be nice to make it dynamic or some other solution.)
+    //
+    // But the rest of the code should use get_input_channels()
+    // to find how many we are actually using.
```

**Comment by Tilps** [comment]
I added a comment.
'Very early, very quick tests' suggest this fix is at least +100Elo in self play at training type visit counts.

**Comment by dubslow** [comment]
I think our next priority needs to be a lot more testing code, that something like this went unnoticed for so long is not a good sign for the health of the codebase

**Comment by Tilps** [comment]
Testing still positive Elo, but down from previous highs. +40Elo after 35 games.  I am using net 245, since I had it handy and thought that overtraining might obfuscate the win.

**Pull request merged**
