### PR TITLE
[WIP] Improve time management

### PR DESCRIPTION
**Pull request by jjoshua2**
Currently timemanage means it never uses all of its time. Increasing slowmover from 89 to 100 so it will use more time. Continuing to test to get some elo numbers here...

### CODE REVIEW

**Comment by jjoshua2** [comment]
tested a few games at 40/30s at got 1-0-2.
still 1080 ti tried 45s+1
```Score of lcz100 vs lczero 4 FpuTime: 2 - 1 - 8 [0.545]
Elo difference: 31.67 +/- 109.93```

**Comment by jjoshua2** [comment]
40/15s + 1 increment
```
Score of lcz100 vs lczero 4 FpuTime: 26 - 19 - 27 [0.549]
Elo difference: 33.89 +/- 64.22
```

**Comment by jjoshua2** [comment]
@Chad on discord helped me test 100 and 178 values. 178 was +50 something elo at 480+5. Both 100 and 178 were regressions with short sudden death controls like 30s/game.

**Comment by jhellis3** [comment]
Pulled some stats from various sources and came up with 3 values to test: 111, 123, 144.

Small round-robin is currently underway.

**Comment by jhellis3** [comment]
Also important to note that with values over 100, losses on time are possible even with increment, so we will need to a proper hard cap for time.

**Comment by jjoshua2** [comment]
That's probably why sudden death elo regressed even though all others increased.

**Comment by jhellis3** [comment]
Slow Mover 111 ended up winning the tournament by a small margin, however many of its wins came on time losses which occurred even with the 200 millisecond increment.

I have simplified the time code further and implemented the max time cutoff, so that we can now experiment with higher time usage when the best move changes (similar to what SF does).
https://github.com/glinscott/leela-chess/compare/master...jhellis3:time_update

I am rerunning the tournament to see if the results change with proper cutoff and check for time losses.

**Comment by jhellis3** [comment]
Ok, I was finally able to complete a tournament without any time losses (and uncovered another TM bug along the way). 123 edged out 144 for first and 111 came in a distant 3rd.  Currently, the optimal value is likely between 123 and 144.

Part of me thinks we should ideally try to stick with 89 and bonus time for moves with low certainty similar to what Stockfish does.  On the other hand, due to the search cutoff we use, we already have a sort of maximally efficient easy move implementation.  In this light, simply increasing the Slow Mover multiplier default might be "good enough."

At any rate, I'll leave it to your discretion as to how to proceed.

**Comment by killerducky** [comment]
1) This PR is outdated since the TM code was reworked, so I'm going to close this.

2) @careless25 is doing a bunch of tests with slowmover as well. I hope @jjoshua2 @jhellis3 and @careless25 can get together and decide what to do next.

I think careless25 has found some values for slow and fast games. We should try to figure how to get the code to work for all timecontrols by default in a reasonable way.

**Comment by careless25** [comment]
```
5+0, 2 threads, 50 slow mover, nps: 1500-2400, depth: 19-21
1+0, 2 thread, 50 slow mover, nps: 1500-1900, depth 17-18
1/4 +0, 2 thread, 50, nps: 1200-1500, depth 14-15 (doesn’t flag easily)
```

Running on Lichess. GTX 1060 6GB. 

I will keep updating as I get more data.

**Comment by careless25** [comment]
Let me know what slowmover/threads you want me to test out and on which time controls.

**Comment by jhellis3** [comment]
There is currently a bug affecting no increment & very low increment time controls. I will submit a fix tonight or tomorrow for that, until then I wouldn't put much stock any results for those time controls.

**Comment by careless25** [comment]
@jhellis3 Also noticed that sometimes the `N` value is really low (less than 1%). Is this normal? Doesn't seem right.

**Comment by careless25** [comment]
Once the fix is in, please PM me the windows binary on discord, I can start running tests on Lichess. Thanks!

**Pull request closed without merging**
