### PR TITLE
Add parralel upload for the game, try to make a more unique ID for multithreading

### PR DESCRIPTION
**Pull request by Uriopass**
This is an answer for issue #114 and #132 
Although if you have a fast GPU you will still have to run mutiple client.exe but it will be far easier.

### CODE REVIEW

**Comment by glinscott** [comment]
Awesome, thanks!  Will get this merged soon, have the upcoming match support, and this should roll out as part of that upgrade.

**Comment by Uriopass** [comment]
You did not try to merge it with the new release ? :/ I'll see if I can fix the merge conflict tonight

**Comment by Uriopass** [comment]
Note that PID now works on windows, so most of the code is useless. Just add "go" in front of uploadGame and it will be mostly equivalent.

**Comment by glinscott** [comment]
Yeah, sorry I couldn't get this in last night.  Limited time!  Will get this merged tonight.

**Comment by Uriopass** [comment]
Don't! The pid works now, just use the "go" in front of uploadGame to make it async.

**Pull request closed without merging**
