### PR TITLE
Implement dynamic temperature

### PR DESCRIPTION
**Pull request by jhellis3**
When --dynamictemp is enabled, the temperature is reduced as
decisiveness increases.

The current implementation is a simple linear reduction up to a preset amount (currently 90%).

### CODE REVIEW

**Comment by jkiliani** [comment]
I looked at this code, and while it should do what you intend, is it actually desirable to use such a control mechanism for temperature? For the opening this should work, sure, but let's say we have a case of an endgame that is drawn if neither side blunders (and the net knows that)? Would this not result in an effective temperature near 1 for all equal positions, including endgames, and induce a blunder on one side or the other?

**Comment by jjoshua2** [comment]
If there is a blunder you want it to be punished. So resigning or lowering
temp afterwards is the way to do that. Google did it the former way. But
either way should work. Doing nothing will put a lower limit on how good
the value net can get.

**Comment by jhellis3** [comment]
@jkiliani Indeed, this only addresses half of the issue - preserving the integrity of a decisive advantage, though it should also be somewhat beneficial for fortress type positions.  

Ideally, this would be used in conjunction with temp decay, which should work well for endgame type draws as those positions typically take quite a few ply to reach.

The main question/concern I had is the maximum amount of reduction to apply.  Currently, it is set to 90%, so at 100% win/loss rate, t=1 becomes 0.1, 90% win/loss rate it is 0.19, and 80% is 0.28.  These seem like reasonable value to me, but I am not certain...

**Comment by killerducky** [comment]
Can you collect some data showing something about the impact? I don't know exactly what we can find, but you could for example pick 10 training games that show examples of blown games. Rerun from a certain point in the endgame 100 times with current temp setting and 100 times with new temp setting. 

This is just the first idea I thought of, in general I think we need more concrete data to make these sort of decisions on.

**Comment by jjoshua2** [comment]
I was thinking of measuring an elo difference between dynamic temp and temp decay, for a given amount of randomness in games. Like being able to run 1000 games without any duplicates without using direchlet noise or threading, but solely from temperature.

**Comment by jhellis3** [comment]
Rather than collecting data, it was easier just to generate new.  I ran a 100 game tournament of id176 under current training conditions vs --dynamictemp.  Results were 78-19-3 in favor of dynamic temp (+235 Elo), which more or less matches my estimate from the google group thread based on the difference in draw rate from match games to training.  I also forgot and left adjudication on, so the results are actually biased against dynamic contempt and likely not _quite_ as extreme as they are under current training.  

PGN: https://drive.google.com/open?id=17aFTR7bzRC1a0INjdVR2PXDlHLJ8v6QD

**Comment by jkiliani** [comment]
So how would you actually apply this? For training games?

One thing I really have to mention is that I picked the logarithmic decay schedule in --tempdecay for a reason. Very small temperatures (<1/4) are almost the same in effect as greedy move selection already, so I'm somewhat concerned that this in its current implementation simply would not provide enough randomness for training games to avoid high correlation between positions. The idea is interesting but I think the dynamic scaling needs some tuning.

**Comment by jkiliani** [comment]
I plotted the current formula, as well as the alternative I'm proposing, with different scaling factors.
temperature

Main differences are that with my formula, small deviations from a balanced board would do little to affect root move temperature, and that values for decisive games are not dropping as low. (Which in my opinion is good since most serious blunders are avoided by just making the 1-visit moves impossible to choose, but allow moves that still get a reasonable visit number).

Combining this formula with temperature decay would be easy by the way. The log term would simply then include both the board evaluation term and the current one with ply_count. I should have picked a higher denominator to the ply count by the way, I now realised that for self-play purposes, even --tempdecay 1 is already a rather fast decay especially when combined with a board eval term.

**Comment by mooskagh** [comment]
I'm not sure I understand but what's going on here is it allows high
temperature (e.g. encourages blunders) when position is drawn and
discourages when it's won/lost. Why is that? I don't understand the
motivation here, why is it "safer" to blunder when it's drawn than when
position is won.

**Comment by jkiliani** [comment]
I think the point behind this is that when we have balanced positions, there's no harm from a training perspective and a lot of benefit from allowing as much move selection variability as possible, since no major blunders happened that need to be trained out of the net. On the other hand, for a decisive position it's advantageous to reduce the chance of further blunders that could reverse the effects of the first blunder, or there's no pressure from the value head training target to fix the policy that led the original blunder in the first place.

It's a refinement on the idea of tempdecay, to only make move selection more deterministic when there's a reason to do so, for training purposes. For match games I see no reason to divert from simply using a temperature that decays throughout the game at a relatively rapid pace.

**Comment by mooskagh** [comment]
Ok, for training games it makes sense.
Not sure if that will have any hidden effects though.

I mean it's already so that it doesn't just try to maximize wining chance
by picking a move, but also tries to minimize harm in case it will blunder
later. It doesn't sound like a good thing to me.

**Comment by Akababa** [comment]
It seems that leela's main weakness atm is the endgame, but wouldn't a temperature scheme like this tend to reach the endgame less often?

**Pull request closed without merging**
