### PR TITLE
Update UCI.cpp

### PR DESCRIPTION
**Pull request by jjoshua2**
should fix https://github.com/glinscott/leela-chess/issues/147#issuecomment-374644844

### CODE REVIEW

**Comment by jjoshua2** [comment]
currently it says unknown command quit quit and then quits. Saying command twice is probably another bug

**Comment by mooskagh** [comment]
It's token and command. That's for debug purposes, sounds fine.

**Comment by jjoshua2** [comment]
then maybe it should say unknown command + cmd + (debug: parsed as + token + )

**Comment by glinscott** [comment]
Fixed in https://github.com/glinscott/leela-chess/pull/143

**Pull request closed without merging**
