### PR TITLE
#338 Issue: Re-enabling Supervised Learning.

### PR DESCRIPTION
**Pull request by Zeta36**
#338 Issue: Re-enabling Supervised Learning. Also fixing some pgn parser bugs: 
1) Fixing a problem because some PGN files have this movement format: 1.d4 (no space after the dot) instead of 1. d4 (pgn.cpp lines 68 to 76).
2) Skipping correctly the comments. It's not enough to check for the opened char '{', we have to take care we found the closer '}' before continuing. (pgn.cpp line 59).
3) If 'cfg_supervise' is not empty we are generating supervised data and so we don't need to load and initialize a network from a file (main.cpp line 373 & 369).

### CODE REVIEW

**Comment by killerducky** [comment]
Can you please change the tabs back to spaces?

**Comment by Zeta36** [comment]
Ok, I'm sorry.

**Comment by killerducky** [comment]
No problem, thanks for doing this. Looks like master needs to be merged into next again. I will do that tonight and try to look at this.

**Comment by Zeta36** [comment]
Perfect :).

**Comment by Zeta36** [comment]
I had some conflicts with the current pgn.cpp file but I think my changes are better than those currently in 'next' branch:
1) The current pgn.cpp does not take into account that some pgn files have this movement format: 1.d4 (no space after the dot) instead of 1. d4.

For example, imagine this: 1.e4 e6 2.d4 d5 3.Nd2 c5...

In the current file we have:

```
// Skip the move numbers
    if (s.back() == '.') {
      continue;
    }
```

but this fails because as I say there is some PGN files with a valid format where the first movement is right after the dot without space:  1.d4 (no space after the dot) instead of 1. d4

I fixed this using the master version of the pgn.cpp file and doing the changes needed to attend both formats (with and without spaces after the dot).

2) Also the way it tries to skip comments  is wrong since some comments have various words and we need to iterate until we find the end char '}' because in other case after continue; we get with "is_ >> s;" a word in the middle of the comment. The correct way is to iterate like I did in line 59.

For example, imagine this: ...48. Rh1 Rxd7 49. Re1 {Black forfeits on time} 1-0

In the current file we have:

```
// Skip comments
    if (s.front() == '{' || s.front() == '[' || s.back() == '}' || s.back() == ']') {
      continue;
    }
```
But then later after the continue the line:

`is_ >> s;`

would fill s = "forfeits" what it's wrong.

We need to do the do{..}while(..); I used to reach the '}' before continuing.

**Comment by killerducky** [comment]
I tried fixing the merge conflict by updating next and toggling the target branch. I guess the problem is one of the intermediate commits on pgn.cpp. Can you please redo this? Maybe squash and/or rebase it.
Your call on doing `push -f` or just making a new PR.

**Comment by Zeta36** [comment]
Ok. I'll try with a new PR.

**Pull request closed without merging**
