### PR TITLE
Update main.go

### PR DESCRIPTION
**Pull request by jjoshua2**
Make uploads async according to @Uriopass earlier pull that is invalidated now that pid works in windows

### CODE REVIEW

**Comment by glinscott** [comment]
I think we have a race here if lczero tries to delete the training.0.gz and create a new one before the goroutine gets to it.

**Comment by glinscott** [comment]
(Also, isn't this overtaken by https://github.com/glinscott/leela-chess/pull/153?)

**Comment by Uriopass** [comment]
Note that this worked without race conditions because in my code a different directory was created for each game, which is not the case here. The time won by going async was very small anyway.

**Comment by jjoshua2** [comment]
It is duplicated by #153, but this is simpler, and less controversial, so I thought it could be committed sooner.

**Comment by glinscott** [comment]
I actually think #153 is strictly better :).  If you agree, we can close this one and get #153 merged.

**Pull request closed without merging**
