### PR TITLE
Winograd

### LINKED ISSUE #10: Port winograd implementation from leela-zero
Once it's stabilized, currently at https://github.com/gcp/leela-zero/tree/winograd

### PR DESCRIPTION
**Pull request by glinscott**
Validating using the bench function that CPU/GPU implementations of winograd match exactly the previous versions.

However, still on hold for now, as multi-threaded performance is actually worse than single threaded performance for some reason!

```
With command:
./lczero --weights weights.txt -t2 -p10000 --noponder

winograd 1 thread:
10000 visits, 340007 nodes, 10000 playouts, 2415 n/s

winograd 2 threads:
10001 visits, 340378 nodes, 10001 playouts, 2188 n/s

master 1 thread:
10000 visits, 340007 nodes, 10000 playouts, 2040 n/s

master 2 threads:
10001 visits, 344601 nodes, 10001 playouts, 3205 n/s

# CPU timings
./lczero --weights weights.txt -t1 -p2000 --noponder --start="bench"
master 1 thread cpu:
2000 visits, 67914 nodes, 2000 playouts, 306 n/s

master 2 thread cpu:
2001 visits, 67667 nodes, 2001 playouts, 571 n/s

winograd 1 thread cpu:
2000 visits, 67914 nodes, 2000 playouts, 405 n/s

winograd 2 thread cpu:
2001 visits, 67692 nodes, 2001 playouts, 647 n/s
```

Resolves #10.

### CODE REVIEW

**Comment by jkiliani** [comment]
Did you also port the tuner? Without tuning, Winograd is often worse than direct convolutions.

**Comment by glinscott** [comment]
@jkiliani yes, it's ported over.  You can see winograd 1 thread is a bit faster than master 1 thread, but it loses badly at 2 threads (and actually gets slower overall).  So something is strange here.

**Comment by jkiliani** [comment]
Good question, but the Winograd implementation on Leela Zero also had people reporting very different improvement margins based on their hardware. Maybe the smaller board compared to Go reduces the benefit of Winograd transform?

Even if Winograd actually ends up not being an improvement for leela-chess, this may change for larger networks with more filters. The benchmarks I've seen all suggest that the benefits of Winograd increase with the width of the neural net.

**Comment by gcp** [comment]
On my GTX 1060, with Leela, I go from t=1 2000 p/s to t=2 3000p/s, but drop down to ~2800 p/s with t=3 and t=4.

At some point the CPU is fast enough to keep the GPU fully fed, and the extra threads are just overhead. (This is why Leela in non-self-play mode defaults to two threads).

Being slower with 2 already though, that's a bit unexpected, and Winograd vs direct shouldn't really make much difference there.

**Comment by glinscott** [comment]
Ok, here is something interesting, I ran two instances of the winograd code in parallel:
10000 visits, 340007 nodes, 10000 playouts, 1785 n/s
10000 visits, 340007 nodes, 10000 playouts, 1736 n/s

So the GPU is capable of supplying 3500 n/s roughly.  Something must be going wrong in the threading.

**Comment by glinscott** [comment]
Doing some profiling, and the reason the 2 thread version is slower is because of the OpenCL driver on Linux :(.  It's doing some pretty inefficient stuff with mutexes internally.

Putting a lock around the call to opencl_net.forward() restores the 2 threaded version performance to 2400 n/s.  But it's still much slower than the original version on 2 threads.  Extremely strange...

**Comment by glinscott** [comment]
Merging this though, as it's better to have higher single threaded performance.  We can just run more workers in parallel, and that seems much safer from a performance perspective.

**Comment by gcp** [comment]
The person who just added multi-GPU support noticed the same as well:
https://github.com/gcp/leela-zero/commit/5855e0fca6713d3f75ec6d13088cc0c3826908a7#diff-7167e6046566ce31562bf0583cc9a166R148

(Just wondering, did you use std::mutex or an SMP::Lock? In this case you need a real mutex)

**Comment by glinscott** [comment]
@gcp ah, interesting.  I was using an SMP::Lock.

**Pull request merged**
