### PR TITLE
[WIP - Broken] Implement tree reuse.

### PR DESCRIPTION
**Pull request by killerducky**
I'm going to run a test tournament between this and latest next to check it more.

If you compile debug mode you'll see these messages:
`update_root, 1101 -> 96 nodes (8.7% reused)`

### CODE REVIEW

**Comment by jkiliani** [comment]
How are you testing this: -p 800 of current /master, versus -v 800 of this pull?

**Comment by killerducky** [comment]
OMG I forgot! I meant to add support for -v and just switch it to -v800 instead of -p800. What the current code does now is identical to -v800 with tree reuse, even though it is called -p800. 

I'll update the code here in a bit.

**Comment by jkiliani** [comment]
Cool! Could you please also do a PR with the noised-root fixed FPU reduction after this?

I'd do it but I don't know how to make branches in git...

**Comment by jkiliani** [comment]
This compiles with no problem for you? I get an Error:
```
UCTNode.cpp:392:16: error: no member named 'undo_move' in 'BoardHistory'
        old_bh.undo_move();
        ~~~~~~ ^
1 error generated.
```

**Comment by killerducky** [comment]
Yes but there is something else wrong, debugging now.

**Comment by killerducky** [comment]
Well so far I can't figure out the problem. It must be related to making and undoing moves on UCTSearch's copy of BoardHistory. shallow_clone might be a problem but I don't know why. Here is the error I get when I play this engine vs next, with a little extra debug prints. Mostly hoping by posting this I will instantly realize what is wrong.  :)

```
debug fnr new_key:-3550874931356715639 this_key:6794118958589081521
debug this_key:6794118958589081521 move:c4d5

 +---+---+---+---+---+---+---+---+
 | r |   | b | q | k | b | n | r |
 +---+---+---+---+---+---+---+---+
 |   | p |   |   |   | p | p |   |
 +---+---+---+---+---+---+---+---+
 | p |   | n |   | p |   |   | p |
 +---+---+---+---+---+---+---+---+
 |   |   |   | p |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   | P | P |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   | N |   |   |
 +---+---+---+---+---+---+---+---+
 | P | P |   |   | B | P | P | P |
 +---+---+---+---+---+---+---+---+
 | R | N | B | Q |   | R | K |   |
 +---+---+---+---+---+---+---+---+

do_move
debug addr 563594059590 563594059590
lc_treereuse: /home/aolsen/projects/lc-stuff/leela-chess/src/Position.cpp:631: void Position::do_move(Move, StateInfo&, bool): Assertion `&newSt != st' failed.
```

**Comment by killerducky** [comment]
I'm calling this function, you can see it puts a new StateInfo object at the back of the states vector, and then passes a pointer to that new object to Position::do_move.
```
void BoardHistory::do_move(Move m) {
  states.emplace_back(new StateInfo);
  positions.push_back(positions.back());
  positions.back().do_move(m, *states.back());
}
```

So how can this assertion fire? I guess it means the object pointed to be st has been destroyed.... omg ok I guess UCI destroyed it and then it got reallocated....

```
void Position::do_move(Move m, StateInfo& newSt, bool givesCheck) {
        
  assert(is_ok(m));
  Utils::myprintf("debug addr %0llx %0llx\n", &newSt, st);
  assert(&newSt != st);
```

**Comment by killerducky** [comment]
```
cat commands1.txt | ./lc_treereuse --threads=1 --seed=1 --weights=$HOME/lcnetworks/id30_839e --noponder --noise -llc_treereuse.log
```

commands1.txt
```
uci
isready
ucinewgame
position startpos
isready
go wtime 10000 btime 10000 movestogo 40
position startpos moves e2e4 e7e5
isready
go wtime 9845 btime 9844 movestogo 39
position startpos moves e2e4 e7e5 g1f3 d7d6
isready
go wtime 9845 btime 9844 movestogo 38
```
```
     13819 Segmentation fault      (core dumped) | ./lc_treereuse --threads=1 --seed=1 --weights=$HOME/lcnetworks/id30_839e --noponder --noise -llc_treereuse.log
```

**Comment by killerducky** [comment]
This is actually with a branch with some logging fixes merged in:

https://github.com/killerducky/leela-chess/tree/treereuse2_log
https://github.com/killerducky/leela-chess/commit/2ae7c0e1d71613c5dc1a9d5721083ac00f4a49fc

**Comment by killerducky** [comment]
A tourny I was running when I found the error at first:
```
cutechess-cli -rounds 100 -tournament gauntlet -concurrency 1 -pgnout results.pgn -debug \
-engine name=lc_treereuse cmd=lc_treereuse arg="--threads=1" arg="--seed=1" arg="--weights=$HOME/lcnetworks/id30_839e" arg="--noponder" arg="--noise" arg="-llc_treereuse.log" tc=40/10 stderr=dbg_treereuse.log \
-engine name=lc_next cmd=lc_next arg="--threads=1" arg="--seed=1" arg="--weights=$HOME/lcnetworks/id30_839e" arg="--noponder" arg="--noise"  arg="-llc_next.log" tc=40/10 stderr=dbg_next.log \
-each proto=uci
```

**Comment by killerducky** [comment]
```
position startpos moves e2e4 e7e5 g1f3 d7d6
isready
readyok
go wtime 9845 btime 9844 movestogo 38

Thread 1 "lc_treereuse" received signal SIGSEGV, Segmentation fault.
Position::repetitions_count (this=<optimized out>) at /home/aolsen/projects/lc-stuff/leela-chess/src/Position.cpp:977
977	    stp = stp->previous->previous;
(gdb) bt
#0  Position::repetitions_count (this=<optimized out>) at /home/aolsen/projects/lc-stuff/leela-chess/src/Position.cpp:977
#1  0x00005555555a0ced in Position::full_key (this=<optimized out>) at /home/aolsen/projects/lc-stuff/leela-chess/src/Position.cpp:134
#2  0x00005555555b91a7 in UCTNode::find_new_root (this=<optimized out>, old_bh=..., new_bh=...) at /home/aolsen/projects/lc-stuff/leela-chess/src/UCTNode.cpp:368
#3  0x00005555555be2fd in UCTSearch::think (this=this@entry=0x5555578035b0, new_bh=...) at /home/aolsen/projects/lc-stuff/leela-chess/src/UCTSearch.cpp:240
#4  0x00005555555b61c0 in (anonymous namespace)::go (is=..., bh=..., search=...) at /home/aolsen/projects/lc-stuff/leela-chess/src/UCI.cpp:114
#5  UCI::loop (start="") at /home/aolsen/projects/lc-stuff/leela-chess/src/UCI.cpp:301
#6  0x0000555555576da7 in main (argc=7, argv=0x7fffffffdd78) at /home/aolsen/projects/lc-stuff/leela-chess/src/main.cpp:348
```

**Comment by killerducky** [comment]
Ok I think I figured out what was wrong. UCI.cpp constructs a new BoardHistory for every move, because UCI protocol gives is a fresh position, which could be any arbitrary position. So when UCI destroys the old BH, all the StateInfo objects get freed. But UCTSearch still has those pointers in it's own shallow_clone of BH.

Bottom line it's not a good idea to keep BH around for long. See #188 for a better way.

**Pull request closed without merging**
