### PR TITLE
Update main.go for better compression

### PR DESCRIPTION
**Pull request by jjoshua2**
This is actually the place that matters, the other was the test function for this.

### CODE REVIEW

**Comment by glinscott** [comment]
This is going to slow down the compact games process a fair bit on the server -- and it's already pretty slow :).

**Comment by glinscott** [comment]
(Oh, also, it's not the place where games are compressed - the client actually does that).

**Comment by jjoshua2** [comment]
This is supposed to better compress 52mb network that you make once and
hundreds of clients download. Saves bandwidth and actually decompresses
faster too. And is still faster to make than the fastest bzip2

**Comment by glinscott** [comment]
Right, but the network is created on the `training/tf` side - these are the training games that are uploaded.

**Pull request closed without merging**
