### PR TITLE
correct path for parser

### PR DESCRIPTION
**Pull request by ganeshkrishnan1**
set the correct updated parser

### CODE REVIEW

**Comment by killerducky** [comment]
Some github usage notes to myself and other devs: I used this PR to test what is happening with github r.e. master/next. I created and merged #460 so now all commits in master are also in next. But the diff in this PR still looked wrong. Then I toggled this PR to master and back to next again. Now the diff looks correct. Maybe if I just waited a little longer it would have fixed itself? Or maybe I will have to use the toggle trick on the other PRs. Will wait a bit and check some other PRs.

Meanwhile looks like it's best to quickly merge master changes into net to prevent this issue.

**Comment by killerducky** [comment]
@ganeshkrishnan1 I'm confused because I don't see parse.py or configparser.py anywhere.

**Comment by ganeshkrishnan1** [comment]
parse.py is missing that's what we have been discussing on #338
It seems train.py has replaced parse.py in which case this pull request needs to be nixed

**Comment by ganeshkrishnan1** [comment]
run train.py by command like this

./train.py --cfg=configs/aihello.yaml --output=/data/aihello.com/training/output

**Pull request closed without merging**
