### PR TITLE
Rewrite the help messages concerning move exploration options

### PR DESCRIPTION
**Pull request by dubslow**
I had to ask in #dev to get any understanding of what they meant, thought it could use some improvement.

(Also includes an ancillary unrelated commit, moving --gpu inside OPENCL #ifdef. Should be both trivial and entirely noncontroversial.)

### CODE REVIEW

**Comment by killerducky** [comment]
Style - some of the lines are very long. gcp has a strict 79 character limit. Personally I think a bit longer is ok but here they can be split more.

I'd like to get to where we are 100% UCI, which means no command line args. So at minimum we need these in UCI. Going further we could actually remove the command line args (after UCI is supported for awhile to allow users time to switch). Not sure if we would go that far.

So if they become UCI options, I think we will be forced to document those separately in a user guide and/or on the wiki. This means the description of e.g. tempdecay can be much less verbose, and users are expected to look at the user guide for more details. Unless `lczero --help` is where the user guide lives? 

@glinscott @Error323 thoughts?

**Comment by dubslow** [comment]
As for style, I saw line 83 is already fairly long, and though I went longer than it, I didn't feel too bad about doing so since it already did. That can all be changed of course.

As for the rest, changing it in the future is all well and good, but in the here and now, this is (I think) an immediate improvement with no future drawback. No risk, plenty of reward.

**Comment by dubslow** [comment]
Many other line lengths within the file are >80 chars, but I reduced the most excessive offenders among my original (plus one existing offender). Perhaps the messages are also slightly clearer now.

**Comment by dubslow** [comment]
I've further rewritten my own additions, hopefully it's even clearer. And any further expansion of the --help message is also warded off by the inclusion of a link to the wiki.

Here's how it looks:

```
$ ./lczero --help
LCZero v0.7 Copyright (C) 2017-2018  Gary Linscott and contributors
Based on:
Leela Chess Copyright (C) 2017 benediamond
Leela Zero Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
Stockfish Copyright (C) 2017  Tord Romstad, Marco Costalba, Joona Kiiski, Gary Linscott
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

If you have further questions about what an option does, see the project wiki:
https://github.com/glinscott/leela-chess/wiki

Allowed options:
  -h [ --help ]                Show commandline options.
  -t [ --threads ] arg (=2)    Number of threads to use.
  -p [ --playouts ] arg        Weaken engine by limiting the number of 
                               playouts. Requires --noponder.
  -v [ --visits ] arg          Weaken engine by limiting the number of visits.
  -r [ --resignpct ] arg (=10) Resign when winrate is less than x%.
  -n [ --noise ]               Before search begins, add Dirichlet noise to the
                               root node policy's move probabilities.
  -m [ --randomize ]           After search is complete, select from the moves 
                               in proportion to their relative values (rather 
                               than 'best only').
  -d [ --tempdecay ] arg       After search is complete, adjust move 
                               probabilities to the power of  1/temperature, 
                               where the temp depends on the specified 
                               tempdecay. Higher decay values are closer to 
                               normal 'best only' choice. -d 0 (temp=1) is 
                               equivalent to --randomize. Temp goes as ~ 
                               1/(1+log(1+plies*decay/50)). -d 1 gives a 
                               move-50-temp of ~0.47. -d 1000 gives a 
                               move-50-temp of ~0.12.
  -s [ --seed ] arg            Random number generation seed.
  -w [ --weights ] arg         File with network weights.
  -l [ --logfile ] arg         File to log input/output to.
  -q [ --quiet ]               Disable all diagnostic output.
  --noponder                   Disable thinking on opponent's time.
  --uci                        Don't initialize the engine until "isready" 
                               command is sent. Use this if your GUI is 
                               freezing on startup.
  --start arg                  Start command {train, bench}.
  --supervise arg              Dump supervised learning data from the pgn.


```

**Comment by dubslow** [comment]
To plead my own case further, another user in Discord just asked the same questions I did about temp, and I referred them to this PR

**Comment by killerducky** [comment]
A few more things: Let's remove the following which don't do anything: noponder and resignpct, and the references to it. For noise and tempdecay, let's include some recommendations to users about avoiding deterministic games. Something like "use --noise and/or --tempdecay 10" to add variety to Lc0's play without weakening it too much".

I'm not sure about including the formulas in tempdecay. How about just leave the high level description, the note about tempdecay=0, and recommend 10. People interested in the exact formula can read the code.

**Comment by dubslow** [comment]
I'd use a decay a lot higher than 10 to retain non-deterministic strength, but points taken

**Comment by killerducky** [comment]
I did some more rewording, what do you think? I don't think users need to see the equations for tempdecay. They just need to know roughly what it does, and have some guidance on what value to use.

**Comment by dubslow** [comment]
I still kinda think that it should at least mention 1) logarithmic in decay, 2) logarithmic in plies. At this point though I'll acquiesce to anything you say just to get it merged.

And also there's recent talk of actually enabling --resign, hence why I left it only commented. I might just revert that commit as well

**Pull request merged**
