### PR TITLE
GPU innerproduct

### PR DESCRIPTION
**Pull request by Ttl**
Move policy head and first value head innerproducts from CPU to GPU. More than twice as fast on my computer than before.

TODO:
* Use faster XGemv kernel from CLBlast (Might require padding)
* Tune XGemv kernel

### CODE REVIEW

**Comment by Error323** [comment]
Sweet sweet speed! Awesome! Thanks!

**Comment by jkiliani** [comment]
Since the Winograd port in LCZero was from mid January, is the output transform/input transform fusion (https://github.com/gcp/leela-zero/commit/479466aaf990fd7717bb939372c29ccfa507701e) also ported yet?

**Comment by Ttl** [comment]
Yes. It was ported in #64.

**Comment by glinscott** [comment]
Verified bench is the same, awesome work, thanks!

**Pull request merged**
