### PR TITLE
Match support

### PR DESCRIPTION
**Pull request by glinscott**
Support matches on the client, and add support for automatically
promoting new networks to best when they finish with more wins than
losses versus the previous.

### CODE REVIEW

**Comment by jkiliani** [comment]
What parameters are planned for the matches? Fixed 100 or 400 games, or SPRT with termination as soon as a decision is made?

Also, are matches going to continue using --noise, or will some other way to ensure the variability of games be used?

**Comment by Uriopass** [comment]
For the moment it's 400 games and it simply checks if wins > losses.
One could try to implement SPRT using [wikipedia](https://en.wikipedia.org/wiki/Sequential_probability_ratio_test) and [the code from Leela Zero](https://github.com/gcp/leela-zero/blob/5958e02cf539d42ee20704b664043036d5c3c18b/validation/SPRT.cpp)

**Comment by Uriopass** [comment]
Just wondering, what are you waiting to merge ? It doesn't seem like anything is missing.

**Comment by glinscott** [comment]
Was testing my local worker for stability before releasing.  Looks good!  So off we go :).

**Pull request merged**
