### PR TITLE
Add basic syzygy endgame table base support to search.

### PR DESCRIPTION
**Pull request by Tilps**
This is just an updated version of #376, with a key bugfix to make it get tablebase hits reliably, based against next and using slightly more recent tbprobe code from official stockfish.

I'm running some tests to see if this version actually is a win on its own, or whether root_probe is needed first. (Or other bugfixes...)

### CODE REVIEW

**Comment by Tilps** [comment]
I did 35 games of 204 vs 204, one with tablebase, other without.  7-3-25 in favour of tablebase. (So probably better, but also big error bars.)

I'm now running a gauntlet against Pawny 1.2 on 40/1 overnight to see if I can get better numbers.

**Comment by Ipmanchess** [comment]
Nice work..is it possible to get a LCZero syzygy compile for windows..then i can also include it in my testings..
or it's to early and when ready it will be possible to download it at LCZero.org?!

**Comment by Tilps** [comment]
Early results of gauntlet are inconclusive.  Unlike the self play where draws were excessively common, tb hasn't had any draws against pawny, but no-tb has about 30% draw rate.  For almost the same scoreline after 15 games each.
Not as much of a difference as I would hope to see, so maybe more bugs to be fixed, or in need of a better strategy for dealing with tablebase draws.

**Comment by Tilps** [comment]
Overnight gauntlet run continued to be pretty much inconclusive, possibly slightly in favour of non-tablebase.  but the draw rate did normalize.

**Comment by Tilps** [comment]
For some reason travis failed to pick up the change I just pushed and instead reran with the same source control status. I don't know how to tell it to try again...

**Comment by Tilps** [comment]
Early signs suggest this version is doing better in gauntlet, will leave running overnight.

**Comment by Tilps** [comment]
Overnight gauntlet not massively convincing, but maybe 40 Elo stronger for 5 piece tablebase using code. More draws and less losses for TB, which matches what I would expect.

**Comment by killerducky** [comment]
+40 Elo with what error?

**Comment by Tilps** [comment]
I've not fed the games into a program which will calculate error bars yet.  But its based on 183 games at this point. 40-37=14 for no-tb vs pawny. 41-27=24 for tb vs pawny. (At 40/1 time controls on my machine.)

**Comment by Tilps** [comment]
After 200 games it was +35, and I'd estimate the error bars as being +/- 40 for the delta.

I found a bug which could cause sub-optimal move selection though - so I've pushed an update and I am starting my gauntlet again while I go to work.

**Comment by Tilps** [comment]
Another 200 games after my fix, this time +42, similar error bars.  At about 150 games it was up +80, but can't read too much in to that.

**Pull request merged**
