### PR TITLE
Add FPU tuning options, search depth tracking

### PR DESCRIPTION
**Pull request by jkiliani**
Adds multiple tuning options for each parameters and set USE_TUNER active by default. Also adds search depth tracking. Implements three methods for FPU calculation, including static parent, dynamic parent, and dynamic with virtual loss. Adds virtual loss increment to configurable parameters.

### CODE REVIEW

**Comment by jkiliani** [comment]
With this PR, the search now supports three methods for FPU calculation, by static parent evaluation, dynamic parent, and dynamic parent affected by virtual losses. While the last was originally an oversight, my tests with Id 129 indicate it actually performs best among all FPU reduction methods:
```
lc_00_dyn results: 15 - 16 - 16
lc_01_dyn results: 19 - 15 - 13
lc_02_dyn results: 14 - 17 - 17
lc_00_vl results: 26 - 9 - 12
lc_01_vl results: 17 - 13 - 17
lc_02_vl results: 24 - 9 - 14
lc_00_stat results: 4 - 34 - 8
lc_01_stat results: 12 - 18 - 16
lc_02_stat results: 14 - 14 - 19
```
I propose to keep all methods within the code until we can safely eliminate some of them if tuning shows them to be consistently worse with multiple nets.

Search depth tracking is implemented along with this, I thought it useful to see the effect of FPU reduction on the search tree shape. I didn't completely replace the current "search depth", would this be a sensible change?

**Comment by killerducky** [comment]
I just skimmed this very briefly, couple points:

1) UCI specifies valid tokens, you should use `seldepth` not `max depth`. Any token not specified by UCI in the info section can only be displayed using `info string blah` instead. That's why we removed `winrate`.

http://wbec-ridderkerk.nl/html/UCIProtocol.html

2) I think m_maxdepth needs to be atomic, because multiple threads are going to write it.

**Comment by jkiliani** [comment]
Ah ok thanks, I'll look into that.

**Comment by killerducky** [comment]
I see fake depth is now actually larger than the max depth, so we should either change it or eliminate it. I think the most fun thing would be to report the min depth, so observers get a feel for how aggressive LZ's pruning is. But I think that might be too expensive, seems you have to do a width-first search of the entire tree. It might be easiest to just report max depth only (as depth because you cannot report seldepth only).

**Comment by jkiliani** [comment]
So we change the info output from whenever fake depth increases, to whenever actual seldepth does?

**Comment by killerducky** [comment]
But we could have up to 40 million UCTNode objects, so that is expensive in memory.

**Comment by mooskagh** [comment]
Alternatively, we can compute average depth of leaves.

Every node stores sum of node depths below it, and number of leaves, on
expansion propagate changes up.
But I like "full depth" more than "average depth", especially as it needs
less memory.

**Comment by mooskagh** [comment]
Having 1 byte for depth is fine, 40Mb is manageable..
Alternatively, we can do depth-limited search periodicaly or when showing
info, as I doubt I ever saw full depth to be equal to 3, and surely never
saw 4 or more. :)

**Comment by jkiliani** [comment]
I now changed max depth in the info string to seldepth, and converted m_maxdepth to an atomic. Sample info output now:
```
info seldepth 2 nodes 2 nps 22 score cp -1013 time 44 pv e2e4 e7e6
info seldepth 2 nodes 2 nps 22 score cp -1013 time 45 pv e2e4 e7e6
info seldepth 3 nodes 5 nps 47 score cp -479 time 85 pv e2e4 e7e6 d2d4 d7d5
info seldepth 4 nodes 7 nps 55 score cp -365 time 108 pv e2e4 e7e6 d2d4 d7d5 e4e5
info seldepth 5 nodes 11 nps 64 score cp -260 time 155 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5
info seldepth 6 nodes 17 nps 64 score cp -182 time 248 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3
info seldepth 7 nodes 21 nps 62 score cp -154 time 322 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5
info seldepth 8 nodes 63 nps 68 score cp -57 time 911 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5
info seldepth 9 nodes 75 nps 68 score cp -48 time 1089 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2
info seldepth 10 nodes 104 nps 69 score cp -36 time 1497 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2 c5d4
info seldepth 11 nodes 153 nps 70 score cp -25 time 2160 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2 c5d4
info seldepth 12 nodes 248 nps 76 score cp -13 time 3255 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2 c5d4 c3d4 b8c6
info seldepth 13 nodes 258 nps 76 score cp -13 time 3389 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2 c5d4 c3d4 b8c6 g1f3
info seldepth 14 nodes 364 nps 82 score cp -7 time 4434 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2 c5d4 c3d4 b8c6 g1f3 g8e7
info seldepth 15 nodes 376 nps 82 score cp -7 time 4576 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2 c5d4 c3d4 b8c6 g1f3 g8e7 f1d3
info seldepth 16 nodes 1041 nps 90 score cp 1 time 11502 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2 c5d4 c3d4 b8c6 g1f3 g8e7 f1d3 e7f5
info seldepth 17 nodes 1059 nps 91 score cp 1 time 11684 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8a5 b1d2 c5d4 c3d4 b8c6 g1f3 g8e7 f1d3 e7f5
info seldepth 18 nodes 1419 nps 94 score cp 2 time 15103 pv e2e4 c7c5 c2c3 e7e6 g1f3 d7d5 e4e5 d5d4 g2g3 b8c6 d2d3 g8e7 f1g2 e7g6
info seldepth 19 nodes 2629 nps 101 score cp 4 time 25967 pv e2e4 c7c5 c2c3 e7e6 g1f3 d7d5 e4e5 d5d4 g2g3 b8c6 d2d3 g8e7 f1g2 e7g6
info seldepth 20 nodes 3362 nps 102 score cp 4 time 33081 pv e2e4 c7c5 c2c3 e7e6 g1f3 d7d5 e4e5 d5d4 d2d3 b8c6 g2g3 g8e7 f1g2 e7g6 d1e2 d4c3
```
By the way, I got to these search depths by setting --fpu_vl and --virtual_loss=10 with -v 5000. Without virtual loss in the FPU reduction, I get seldepth 17 with 5000 visits from the starting position.

**Comment by jkiliani** [comment]
Agreed that having the full search depth as well would be very nice, but it would definitely take me somewhat longer to get that working too...

**Comment by jkiliani** [comment]
Result of my first tuning tournament for Id 129:
```
Rank Name                          Elo     +/-   Games   Score   Draws
   1 lc_00_vl                      139      90      50   69.0%   26.0%
   2 lc_02_vl                      108      85      50   65.0%   30.0%
   3 lc_01_vl                       42      79      50   56.0%   36.0%
   4 lc_01_dyn                      21      82      50   53.0%   30.0%
   5 lc_00_dyn                       7      79      50   51.0%   34.0%
   6 lc_02_stat                      0      74      51   50.0%   41.2%
   7 lc_02_dyn                     -21      77      50   47.0%   38.0%
   8 lc_01_stat                    -56      79      50   42.0%   36.0%
   9 lc_00_stat                   -268     109      51   17.6%   19.6%
```
I'm now running a second tournament on the same net, but with the virtual loss all using 0 fixed FPU reduction but variable values for virtual loss (I'm trying 1, 3 and 6 for now).

**Comment by jkiliani** [comment]
PR seems bugged, matches in cutechess-cli are getting stuck. Must have something to do with the search depth tracking I think...

**Comment by jkiliani** [comment]
I noticed in the sample output above that the info eval is really off at low visit count when multithreading. The reason for that is that get_eval is used here, which includes virtual loss. We can now avoid this with get_raw_eval, so I'll replace this.

**Comment by jkiliani** [comment]
Caution, latest commit is not yet thread-safe. I pushed it so the strange behaviour regarding the expansion of zero-visit nodes during multithreading could be investigated.

**Comment by jkiliani** [comment]
I just cancelled the first combined tuning test of regular FPU reduction and FPU reduction from virtual loss, with Id 125:
```
Rank Name                          Elo     +/-   Games   Score   Draws
   1 lc_00_9                        56      58      88   58.0%   38.6%
   2 lc_02_0                        45      52      86   56.4%   50.0%
   3 lc_01_9                        24      56      87   53.4%   42.5%
   4 lc_01_3                        24      60      87   53.4%   33.3%
   5 lc_02_9                       -28      60      87   46.0%   34.5%
   6 lc_01_0                       -28      56      87   46.0%   41.4%
   7 lc_00_0                       -28      62      87   46.0%   29.9%
   8 lc_02_3                       -28      59      86   45.9%   36.0%
   9 lc_00_3                       -36      62      87   44.8%   29.9%
```
Seems somewhat inconclusive to be honest, the only thing that looks apparent is that FPU reduction one way or another does help. I'm now switching this test to Id 162.

**Comment by jjoshua2** [comment]
Is the bottom one 00 03 the current method? And 00 00 is nothing?

**Comment by jkiliani** [comment]
Yes correct, 00_3 is the current method (or at least should be, for any node that does not have virtual loss from multiple threads active). And it looks like it may well already be good enough:
```
Rank Name                          Elo     +/-   Games   Score   Draws
   1 lc_00_3                        52      60      81   57.4%   38.3%
   2 lc_00_9                        35      67      80   55.0%   25.0%
   3 lc_01_3                        17      66      80   52.5%   27.5%
   4 lc_02_3                        13      55      80   51.9%   48.8%
   5 lc_01_0                         4      61      80   50.6%   36.3%
   6 lc_00_0                         0      63      80   50.0%   32.5%
   7 lc_01_9                       -17      61      80   47.5%   37.5%
   8 lc_02_0                       -22      58      80   46.9%   43.8%
   9 lc_02_9                       -83      60      81   38.3%   39.5%
```
Here, no or only a bit of regular FPU reduction together works best (for Id 162). Running Id 170 now.

**Comment by jkiliani** [comment]
The third combined tuning run, with Id 170:
```
   1 lc_01_0                       142      92      49   69.4%   24.5%
   2 lc_00_9                        49      75      50   57.0%   42.0%
   3 lc_01_3                        36      67      49   55.1%   53.1%
   4 lc_00_3                        28      81      50   54.0%   32.0%
   5 lc_01_9                       -28      73      50   46.0%   44.0%
   6 lc_00_0                       -28      83      49   45.9%   30.6%
   7 lc_02_3                       -57      78      49   41.8%   38.8%
   8 lc_02_9                       -63      83      50   41.0%   30.0%
   9 lc_02_0                       -70      84      50   40.0%   28.0%
```
Here, regular FPU reduction with no simulated virtual loss does best by a decisive margin. Running Id 181 now.

**Comment by jkiliani** [comment]
Id 181:
```
Rank Name                          Elo     +/-   Games   Score   Draws
   1 lc_01_9                        58      83      42   58.3%   40.5%
   2 lc_00_3                        58      75      42   58.3%   50.0%
   3 lc_01_0                        42      83      42   56.0%   40.5%
   4 lc_00_9                        42      86      42   56.0%   35.7%
   5 lc_02_0                         0      84      42   50.0%   38.1%
   6 lc_02_3                        -8      75      42   48.8%   50.0%
   7 lc_01_3                       -17      81      42   47.6%   42.9%
   8 lc_00_0                       -67      81      42   40.5%   42.9%
   9 lc_02_9                      -111      84      42   34.5%   40.5%
```
I think using simulated VL works quite well in a large majority of cases, but regular FPU reduction with 0.1 is still competitive. I'll compile a summary of the tests soon (maybe this weekend?), and I'd still like to do a test with an adaptive virtual loss to get around the problem that a fixed simulated VL will work very differently at low visit counts than at high.

**Comment by gcp** [comment]
Aren't these results extremely random with so few games?

**Comment by jkiliani** [comment]
Yes I agree absolutely, the statistics are weak (just the best I can do atm). I still think multiple weak statistics on multiple nets are better than somewhat stronger statistics on a single net, since that way you wouldn't even see if the result can be safely generalised to other networks.

**Comment by gcp** [comment]
Well, if you add up the scores from all the different nets, does any method come out as superior with any kind of statistical certainty?

**Comment by gcp** [comment]
Anyway, the point I'm trying to make is: try to figure out some way to proceed! If you have very limited testing resources, then make your best picks (based on available data) at what could help and then try to provide it they do.

If you want to test too many combinations things quickly become hopeless because you'll never manage to make a solid conclusion, and you end up floundering.

It's better to have a 50 Elo improvement in the codebase while a 55 Elo one would have been possible, than not to have anything at all in the end.

**Comment by jkiliani** [comment]
Thanks for the advice. I think your run was valuable because it showed that we definitely can't assume cfg_puct is currently even close to optimal.

I think what I'll do is actually remove the current method of FPU reduction, implement my best guess to what should work with simulated virtual loss, tune with tune parameters (cfg_puct and the new FPU reduction method) hopefully helped by some more powerful machines, and then do a straight comparison to current master.

**Comment by killerducky** [comment]
@jkiliani sounds like a good plan, but about "remove the current method of FPU reduction", I think we should leave the code such that it's easy to switch to different methods. Just limit testing to your best guess vs the current next code base. Later when we're more confident we can clean the code to only do one way.

**Comment by jkiliani** [comment]
@killerducky I read your last comment a little too late, already implemented #438 and starting to test it now. I am however also testing against current next, along with tuning puct and fpu_reduction (with the proposed method).

**Pull request closed without merging**
